package com.owaspdemo.a04_cryptographic_failures;

import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.time.Instant;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * A04:2025 - Cryptographic Failures
 *
 * SECURE: Generates magic link tokens with proper cryptographic practices.
 *
 * Fixes:
 * 1. Strong 256-bit random key (generated by JJWT)
 * 2. 5-minute expiry
 * 3. Single-use enforcement (token ID tracked and invalidated)
 * 4. Token bound to specific email claim
 */
@Service
public class SecureMagicLinkService {

    // GOOD: Cryptographically strong random key (256-bit)
    private final SecretKey strongKey = Jwts.SIG.HS256.key().build();

    // Track used token IDs to prevent replay
    private final Set<String> usedTokenIds = ConcurrentHashMap.newKeySet();

    public String generateToken(String email) {
        String tokenId = java.util.UUID.randomUUID().toString();

        return Jwts.builder()
                .id(tokenId)
                .subject(email)
                .claim("type", "magic-link")
                .issuedAt(Date.from(Instant.now()))
                .expiration(Date.from(Instant.now().plusSeconds(300))) // 5 minutes
                .signWith(strongKey)
                .compact();
    }

    public Map<String, Object> verifyToken(String token) {
        try {
            var claims = Jwts.parser()
                    .verifyWith(strongKey)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();

            String tokenId = claims.getId();

            // GOOD: Single-use check — reject if already used
            if (!usedTokenIds.add(tokenId)) {
                return Map.of("valid", false, "message", "Token already used — replay attack blocked");
            }

            return Map.of(
                    "email", claims.getSubject(),
                    "valid", true,
                    "message", "Magic link verified — user authenticated"
            );
        } catch (JwtException e) {
            return Map.of("valid", false, "message", "Invalid or expired token: " + e.getMessage());
        }
    }
}
