FROM node:20-alpine AS build
ARG VITE_VM_HOST
ENV VITE_VM_HOST=${VITE_VM_HOST}
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template
EXPOSE 80 443
