spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/owaspdb
    driver-class-name: org.postgresql.Driver
    username: owasp
    password: owasp123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: false
